Debug ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -143,10 +143,18 @@ jobs:
         include:
           - rust: stable
             toolchain: stable
-            # coverage: --enable-coverage
+            coverage: --enable-coverage
           - rust: prev
             toolchain: ${{ needs.prepare-checks.outputs.rust-prev-version }}
     steps:
+      - name: Set CI Profile
+        run: echo "CARGO_PROFILE_DEV_INHERITS=ci-rust" >> $GITHUB_ENV
+      # --------------------------------------------------------------------------------
+      - name: Check disk usage
+        shell: bash
+        run: |
+          df -h
+      # --------------------------------------------------------------------------------
       - name: Setup Rust
         uses: tracel-ai/github-actions/setup-rust@v1
         with:
@@ -161,28 +169,42 @@ jobs:
           mesa-ci-build-version: ${{ env.MESA_CI_BINARY_BUILD }}
           cargo-package-to-clean: burn-tch
       # --------------------------------------------------------------------------------
-      # - name: Install grcov
-      #   if: matrix.rust == 'stable'
-      #   shell: bash
-      #   run: |
-      #     curl -L "$GRCOV_LINK/v$GRCOV_VERSION/grcov-x86_64-unknown-linux-musl.tar.bz2" |
-      #     tar xj -C $HOME/.cargo/bin
-      #     cargo xtask coverage install
+      - name: Install grcov
+        if: matrix.rust == 'stable'
+        shell: bash
+        run: |
+          curl -L "$GRCOV_LINK/v$GRCOV_VERSION/grcov-x86_64-unknown-linux-musl.tar.bz2" |
+          tar xj -C $HOME/.cargo/bin
+          cargo xtask coverage install
+      # --------------------------------------------------------------------------------
+      - name: Check disk usage
+        shell: bash
+        run: |
+          df -h
       # --------------------------------------------------------------------------------
       - name: Tests
         run: cargo xtask ${{ matrix.coverage }} test --ci
       # --------------------------------------------------------------------------------
-      # - name: Generate lcov.info
-      #   if: matrix.rust == 'stable'
-      #   # /* is to exclude std library code coverage from analysis
-      #   run: cargo xtask coverage generate --ignore "/*,xtask/*,examples/*"
+      - name: Check disk usage
+        if: always()  # Runs even if previous steps fail
+        shell: bash
+        run: |
+          df -h
+          du -sh --exclude="*.profraw" *
+          echo ".profraw files:"
+          du -ch *.profraw | grep total || echo "No .profraw files found"
       # --------------------------------------------------------------------------------
-      # - name: Codecov upload lcov.info
-      #   if: matrix.rust == 'stable'
-      #   uses: codecov/codecov-action@v5
-      #   with:
-      #     files: lcov.info
-      #     token: ${{ secrets.CODECOV_TOKEN }}
+      - name: Generate lcov.info
+        if: matrix.rust == 'stable'
+        # /* is to exclude std library code coverage from analysis
+        run: cargo xtask coverage generate --ignore "/*,xtask/*,examples/*"
+      # --------------------------------------------------------------------------------
+      - name: Codecov upload lcov.info
+        if: matrix.rust == 'stable'
+        uses: codecov/codecov-action@v5
+        with:
+          files: lcov.info
+          token: ${{ secrets.CODECOV_TOKEN }}
 
   linux-no-std-tests:
     runs-on: ubuntu-22.04
